# Generated by Django 5.2.4 on 2025-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('quote_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_author', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
