# Generated by Django 5.2.4 on 2025-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(unique=True),
        ),
    ]
