# Generated by Django 5.2.4 on 2025-07-14 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_quote_quote_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('quote_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_community_member', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
