# Generated by Django 5.2.4 on 2025-07-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_communityquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityquote',
            name='quote_community_member',
        ),
    ]
