# Generated by Django 5.2.4 on 2025-08-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_userengagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('copy_count', models.PositiveIntegerField(default=0)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='apis.quote')),
            ],
        ),
    ]
