# Generated by Django 5.2.4 on 2025-08-16 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_quoteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='disliked_quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='liked_quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userengagement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to=settings.AUTH_USER_MODEL),
        ),
    ]
