# Generated by Django 5.2.4 on 2025-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_userengagement_disliked_quotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userengagement',
            name='disliked_quotes',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='liked_quotes',
        ),
        migrations.AddField(
            model_name='userengagement',
            name='disliked_quotes',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='apis.quote'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='liked_quotes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='apis.quote'),
        ),
    ]
