# Generated by Django 5.2.4 on 2025-08-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_remove_userengagement_disliked_quotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='saved_quotes',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='apis.quote'),
        ),
    ]
