# Generated by Django 5.2.4 on 2025-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(),
        ),
    ]
