# Generated by Django 5.2.4 on 2025-08-24 12:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_quote_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='apis_quote_search__fdc10c_gin'),
        ),
    ]
