# Generated by Django 5.2.4 on 2025-08-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_quote_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quote',
            name='apis_quote_search__fdc10c_gin',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='search_vector',
        ),
    ]
