# Generated by Django 5.2.4 on 2025-08-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_remove_quote_apis_quote_search__fdc10c_gin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='communityquote',
            name='quote_genre',
        ),
        migrations.AddField(
            model_name='communityquote',
            name='quote_genres',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='apis.genre'),
        ),
    ]
