# Generated by Django 5.2.5 on 2025-09-02 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_genre_remove_communityquote_quote_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_genre',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_genres',
            field=models.ManyToManyField(blank=True, related_name='quote_set', to='apis.genre'),
        ),
        migrations.AlterField(
            model_name='communityquote',
            name='quote_genres',
            field=models.ManyToManyField(blank=True, related_name='communityquote_set', to='apis.genre'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='apis.userinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
