# Generated by Django 5.2.5 on 2025-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_remove_quote_quote_genre_quote_quote_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_source',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
