# Generated by Django 5.2.5 on 2025-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_genre_name_alter_quote_quote_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
