# Generated by Django 5.2.5 on 2025-09-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_alter_quote_quote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
