# Generated by Django 5.2.5 on 2025-09-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_alter_genre_name_alter_quote_quote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityquote',
            name='quote_genres',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_genres',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='apis.genre'),
        ),
    ]
