# Generated by Django 5.2.5 on 2025-09-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_remove_communityquote_quote_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityquote',
            name='quote_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_quotes', to='apis.genre'),
        ),
    ]
