# Generated by Django 5.2.5 on 2025-09-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_communityquote_quote_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userengagement',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user_profile',
            field=models.JSONField(default=dict),
        ),
    ]
