# Generated by Django 5.2.4 on 2025-10-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_quote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userengagement',
            name='disliked_quotes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='disliked_by', to='apis.quote'),
        ),
        migrations.AlterField(
            model_name='userengagement',
            name='liked_quotes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='liked_by', to='apis.quote'),
        ),
    ]
