# Generated by Django 5.2.4 on 2025-10-23 18:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_create_quote_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='apis_quote_search__fdc10c_gin'),
        ),
    ]
