# Generated by Django 5.2.4 on 2025-12-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_quote_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='disliked_community_quotes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='disliked_by', to='apis.communityquote'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='liked_community_quotes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='liked_by', to='apis.communityquote'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='saved_community_quotes',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='apis.communityquote'),
        ),
        migrations.CreateModel(
            name='CommunityQuoteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('copy_count', models.PositiveIntegerField(default=0)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='apis.communityquote')),
            ],
        ),
    ]
