name: Keep HF Backend Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping HF backend
        run: |
          curl -s https://abdelrhmanmo-sayings-api.hf.space/apis/auth/ > /dev/null
          echo "Pinged successfully"
